spring:
  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations:
        - classpath:database.sql
        - classpath:schema.sql
      data-locations:
        - classpath:data.sql
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;
    username: sa
    password: MyStrong!!Password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  h2:
#    console:
#      enabled: true
  thymeleaf:
    cache: false

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0

mybatis:
  config-location: classpath:mybatis.xml

logging:
  level:
    library.infrastructure:
      datasource: DEBUG