DROP TABLE IF EXISTS 会員,本,蔵書,貸出可能,貸出,返却,予約,予約取消,取置;
DROP SEQUENCE IF EXISTS 貸出ID;
DROP SEQUENCE IF EXISTS 予約ID;

-- スキーマとオブジェクトをリセット
DROP SCHEMA IF EXISTS 書籍 CASCADE;
CREATE SCHEMA 書籍;

DROP SCHEMA IF EXISTS 蔵書 CASCADE;
CREATE SCHEMA 蔵書;

DROP SCHEMA IF EXISTS 会員 CASCADE;
CREATE SCHEMA 会員;

DROP SCHEMA IF EXISTS 貸出 CASCADE;
CREATE SCHEMA 貸出;

DROP SCHEMA IF EXISTS 予約 CASCADE;
CREATE SCHEMA 予約;

DROP SCHEMA IF EXISTS 取置 CASCADE;
CREATE SCHEMA 取置;

-- 会員スキーマ
CREATE TABLE 会員.会員
(
  会員番号 INTEGER PRIMARY KEY,
  氏名   VARCHAR(40) NOT NULL,
  会員種別 VARCHAR(2)  NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 書籍.書籍
(
  本番号  INTEGER PRIMARY KEY,
  タイトル VARCHAR(40) NOT NULL,
  著者   VARCHAR(40) NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 蔵書スキーマ
CREATE TABLE 蔵書.蔵書
(
  蔵書番号 VARCHAR(40) PRIMARY KEY,
  本番号  INTEGER   NOT NULL REFERENCES 書籍.書籍,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.貸出可能
(
  蔵書番号 VARCHAR(40) PRIMARY KEY REFERENCES 蔵書.蔵書,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.貸出中
(
  蔵書番号 VARCHAR(40) NOT NULL REFERENCES 蔵書.蔵書,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.取置中
(
  蔵書番号 VARCHAR(40) PRIMARY KEY REFERENCES 蔵書.蔵書,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 貸出スキーマ
CREATE SEQUENCE 貸出.貸出番号;

CREATE TABLE 貸出.貸出履歴
(
  貸出番号 INTEGER PRIMARY KEY,
  会員番号 INTEGER     NOT NULL REFERENCES 会員.会員,
  蔵書番号 VARCHAR(40) NOT NULL REFERENCES 蔵書.蔵書,
  貸出日  DATE        NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 貸出.返却履歴
(
  貸出番号 INTEGER PRIMARY KEY REFERENCES 貸出.貸出履歴,
  返却日  DATE      NOT NULL,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- 予約スキーマ
CREATE SEQUENCE 予約.予約番号;

CREATE TABLE 予約.予約履歴
(
  予約番号 INTEGER PRIMARY KEY,
  会員番号 INTEGER   NOT NULL REFERENCES 会員.会員,
  本番号  INTEGER   NOT NULL REFERENCES 書籍.書籍,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 予約.未準備
(
  予約番号 INTEGER PRIMARY KEY REFERENCES 予約.予約履歴,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 予約.予約取消履歴
(
  予約番号 INTEGER PRIMARY KEY REFERENCES 予約.予約履歴,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 取置スキーマ
CREATE TABLE 取置.取置履歴
(
  予約番号 INTEGER PRIMARY KEY REFERENCES 予約.予約履歴,
  蔵書番号 VARCHAR(40) NOT NULL REFERENCES 蔵書.蔵書,
  取置日  DATE        NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 準備完了 蔵書でユニーク（同じ蔵書を同時に取置はできない）
CREATE TABLE 取置.準備完了
(
  蔵書番号 VARCHAR(40) PRIMARY KEY,
  予約番号 INTEGER   NOT NULL,
  FOREIGN KEY (予約番号, 蔵書番号) REFERENCES 取置.取置履歴 (予約番号, 蔵書番号),
  取置日  DATE      NOT NULL,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 取置を貸し出した記録
CREATE TABLE 取置.取置解放履歴
(
  予約番号 INTEGER PRIMARY KEY,
  蔵書番号 VARCHAR(40) NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (予約番号, 蔵書番号) REFERENCES 取置.取置履歴 (予約番号, 蔵書番号)
);
-- 取置の期限切れ
CREATE TABLE 取置.取置期限切れ履歴
(
  予約番号 INTEGER PRIMARY KEY REFERENCES 取置.取置解放履歴,
  登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
