AWSTemplateFormatVersion: "2010-09-09"
Description: "library ecs"
Parameters:
  Flavor:
    Type: String
    Default: library
  EnvironmentName:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
  VpcStack:
    Type: String
    Default: "library-development-vpc"

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Flavor}-cluster"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Flavor
          Value: !Ref Flavor
  WebContainerRepository:
   Type: AWS::ECR::Repository
   DeletionPolicy: Retain # 手動で削除する
   Properties:
     RepositoryName: !Sub "${Flavor}-web"
     ImageTagMutability: MUTABLE
     LifecyclePolicy:
       LifecyclePolicyText: |
         {
           "rules": [
             {
               "rulePriority": 1,
               "description": "delete untagged image",
               "selection": {
                 "tagStatus": "untagged",
                 "countType": "imageCountMoreThan",
                 "countNumber": 3
               },
               "action": {
                 "type": "expire"
               }
             }
           ]
         }

Outputs:
  Cluster:
    Value: !Ref Cluster
    Export:
      Name: !Sub "${AWS::StackName}:Cluster"
  WebContainerRepository:
    Value: !Ref WebContainerRepository
    Export:
      Name: !Sub "${AWS::StackName}:WebContainerRepository"

