AWSTemplateFormatVersion: "2010-09-09"
Description: "library vpc"
Parameters:
  Flavor:
    Type: String
    Default: Library
  VpcAvailabilityZones:
    Type: CommaDelimitedList
    Default: "ap-northeast-1a,ap-northeast-1c"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      Tags:
        - Key: Flavor
          Value: !Ref Flavor
        - Key: Name
          Value: !Sub "${Flavor}VPC"
  # ALBが使うので2つのAZが必要
  PublicSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.11.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !Ref VpcAvailabilityZones ]
      Tags:
        - Key: Flavor
          Value: !Ref Flavor
        - Key: Name
          Value: !Sub "${Flavor}PublicSubnet1"
  PublicSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.12.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 1, !Ref VpcAvailabilityZones ]
      Tags:
        - Key: Flavor
          Value: !Ref Flavor
        - Key: Name
          Value: !Sub "${Flavor}PublicSubnet2"
